stages:
    - test
    - deploy

build_it_test_it:
    stage: test
    script:
        - echo "---- Work it. Make it. ----"
        - mkdir build
        - cd build/
        - cmake -DQt5_DIR=/usr/local/opt/qt5/lib/cmake/Qt5 ..
        - make
        - echo "---- Do it. Makes us. ----"
        - echo "Testing coming soon..."
    tags:
        - test
        - homebrew

deploy_it_osx:
    stage: deploy
    script:
        - echo "---- Work it harder. ----"
        - version=$(utils/scripts/version-gen.sh)
        - mkdir build
        - cd build/
        - echo "---- Make it better. ----"
        - cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_DragNDrop=ON -DBUILD_OSX_APPS=ON -DBoost_USE_STATIC_LIBS=ON -DINSTALL_VC_DEMO=ON ..
        - echo "---- Do it faster. ----"
        - make package -j8
        - echo "---- Makes us stronger. ----"
        - mkdir -p ~/Dropbox/VC-Releases/v${version}
        - cp VC* ~/Dropbox/VC-Releases/v${version}
    only:
        - master
    tags:
        - deploy
        - osx
        - static

archive_it:
    stage: deploy
    script:
        - version=$(utils/scripts/version-gen.sh)
        - vershort=$(utils/scripts/version-gen.sh --short)
        - git archive --format=tar.gz -o VC-${vershort}-source.tar.gz HEAD
        - mkdir -p ~/Dropbox/VC-Releases/v${version}
        - cp VC-${vershort}-source.tar.gz ~/Dropbox/VC-Releases/v${version}
    only:
        - master