stages:
    - build
    - test
    - deploy

build:debian:
    image: volcart/vcbuilder-debian:latest
    stage: build
    script:
        - echo $CI_BUILD_REF_NAME   $CI_BUILD_STAGE
        - echo "---- Work it. Make it. ----"
        - git submodule update --init external/
        - mkdir -p build
        - cd build/
        - cmake -DBoost_USE_STATIC_LIBS=ON -DVC_USE_ACVD=ON -DVC_USE_BULLET=ON -DVC_USE_LIBIGL=ON -GNinja ..
        - ninja
    tags:
        - build
        - linux
        - static
        - qt5
        - ninja

test:debian:
    image: volcart/vcbuilder-debian:latest
    stage: test
    script:
        - echo $CI_BUILD_REF_NAME  $CI_BUILD_STAGE
        - git submodule update --init external/
        - mkdir -p build
        - cd build/
        - cmake -DBoost_USE_STATIC_LIBS=ON -DVC_USE_ACVD=ON -DVC_USE_BULLET=ON -DVC_USE_LIBIGL=ON -GNinja ..
        - ninja
        - ninja test
    artifacts:
      name: "${CI_BUILD_STAGE}_${CI_BUILD_REF_NAME}"
      paths:
        - build/Testing/Temporary/
      when: always
      expire_in: 4 weeks
    tags:
        - test
        - linux
        - static
        - qt5
        - ninja

build:osx:
    stage: build
    script:
        - echo $CI_BUILD_REF_NAME   $CI_BUILD_STAGE
        - echo "---- Work it. Make it. ----"
        - git submodule update --init external/
        - mkdir -p build
        - cd build/
        - cmake -DQt5_DIR=/usr/local/opt/qt5/lib/cmake/Qt5 -DVC_USE_ACVD=ON -DVC_USE_BULLET=ON -DVC_USE_LIBIGL=ON -GNinja ..
        - ninja
    tags:
        - build
        - osx
        - homebrew
        - qt5
        - ninja

test:osx:
    stage: test
    script:
        - echo $CI_BUILD_REF_NAME  $CI_BUILD_STAGE
        - git submodule update --init external/
        - mkdir -p build
        - cd build/
        - cmake -DQt5_DIR=/usr/local/opt/qt5/lib/cmake/Qt5 -DVC_USE_ACVD=ON -DVC_USE_BULLET=ON -DVC_USE_LIBIGL=ON -GNinja ..
        - ninja
        - ninja test
    artifacts:
      name: "${CI_BUILD_STAGE}_${CI_BUILD_REF_NAME}"
      paths:
        - build/testing/Temporary/
      when: always
      expire_in: 4 weeks
    tags:
        - test
        - osx
        - homebrew
        - qt5
        - ninja

deploy:osx:
    stage: deploy
    script:
        - echo "---- Work it harder. ----"
        - version=$(utils/scripts/version-gen.sh)
        - git submodule init
        - cd vc-deps/
        - ./build-deps.sh -universal
        - cd ..
        - mkdir -p build
        - cd build/
        - echo "---- Make it better. ----"
        - cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DINSTALL_VC_DEMO=ON -DVC_PREBUILT_LIBS=ON -DQt5_DIR=/usr/local/opt/qt5/lib/cmake/Qt5 -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9 -DCMAKE_OSX_SYSROOT=../vc-deps/build/SDKs/MacOSX10.9.sdk/ ..
        - echo "---- Do it faster. ----"
        - ninja
        - ninja package
        - echo "---- Makes us stronger. ----"
        - version=$(../utils/scripts/version-gen.sh)
        - mkdir -p ~/Dropbox/VC-Releases/v${version}
        - cp VC* ~/Dropbox/VC-Releases/v${version}
    only:
        - master
    tags:
        - deploy
        - osx
        - homebrew
        - prebuilt
        - qt5

archive:
    stage: deploy
    script:
        - version=$(utils/scripts/version-gen.sh)
        - vershort=$(utils/scripts/version-gen.sh --short)
        - git archive --format=tar.gz -o VC-${vershort}-source.tar.gz HEAD
        - mkdir -p ~/Dropbox/VC-Releases/v${version}
        - cp VC-${vershort}-source.tar.gz ~/Dropbox/VC-Releases/v${version}
    only:
        - master
