stages:
    - build
    - test
    - deploy

build_it:
    stage: build
    script:
        - mkdir build
        - cd build/
        - cmake ..
        - make
    tags:
        - test

test_it:
    stage: test
    script:
        - echo "Testing coming soon..."
    tags:
        - test

deploy_it_osx:
    stage: deploy
    script:
        - mkdir build
        - cd build/
        - cmake -DBUILD_DragNDrop=ON -DBUILD_OSX_APPS=ON -DBoost_USE_STATIC_LIBS=ON -DINSTALL_VC_DEMO=ON ..
        - make package -j8
        - version=$(../utils/scripts/version-gen.sh)
        - mkdir -p ~/Dropbox/VC-Releases/v${version}
        - cp VC* ~/Dropbox/VC-Releases/v${version}
    only:
        - master
    tags:
        - deploy
        - osx
        - static