stages:
    - test
    - lint
    - docs
    - collect
    - deploy
    - release

variables:
    MACOSX_DEPLOYMENT_TARGET: "10.13"

### Prototype build jobs ###
.build_script: &build_script
    - mkdir -p build/
    - cd build/
    - echo $CMAKE_CMD
    - $CMAKE_CMD
    - ninja

.test_script: &test_script
    - ctest -V

.build:
    variables:
        EXTRA_CMAKE_FLAGS: ""
    before_script:
        - export CMAKE_CMD="cmake -GNinja $EXTRA_CMAKE_FLAGS .."
    script:
        - *build_script
    rules:
        - if: '$CI_PROJECT_URL =~ /.*gitlab\.com.*/'
          when: never
        - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
        - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
          when: never
        - if: '$CI_COMMIT_BRANCH'

.build_and_test:
    extends: .build
    script:
        - *build_script
        - *test_script
    rules:
        - if: '$CI_PROJECT_URL =~ /.*gitlab\.com.*/'
          when: never
        - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
        - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
          when: never
        - if: '$CI_COMMIT_BRANCH'
    artifacts:
        name: "${CI_BUILD_STAGE}_${CI_BUILD_REF_NAME}"
        paths:
            - build/Testing/Temporary/
        when: always
        expire_in: 4 weeks

### Debian ###
test:debian:static:
    extends: .build_and_test
    stage: test
    needs: []
    image: volcart/vcbuilder-debian:11_v1.static
    variables:
        CMAKE_PREFIX_PATH: "/usr/local/Qt-6.2.3/"
        EXTRA_CMAKE_FLAGS: "-DVC_BUILD_ACVD=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo -DVC_DEVELOPER_WARNINGS=ON"
    tags:
        - docker

test:debian:dynamic:
    extends: .build_and_test
    stage: test
    needs: []
    image: volcart/vcbuilder-debian:11_v1.dynamic
    variables:
        CMAKE_PREFIX_PATH: "/usr/local/Qt-6.2.3/"
        EXTRA_CMAKE_FLAGS: "-DVC_BUILD_ACVD=ON -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo -DVC_DEVELOPER_WARNINGS=ON"
    tags:
        - docker

### macOS ###
.test:macos:static:
    extends: .build_and_test
    stage: test
    needs: []
    variables:
        CMAKE_PREFIX_PATH: "/usr/local/opt/qt6/lib/cmake"
        EXTRA_CMAKE_FLAGS: "-DVC_BUILD_ACVD=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo -DVC_DEVELOPER_WARNINGS=ON"
    tags:
        - test
        - osx
        - homebrew
        - qt6
        - ninja

.test:macos:dynamic:
    extends: .build_and_test
    stage: test
    needs: []
    variables:
        CMAKE_PREFIX_PATH: "/usr/local/opt/qt6/lib/cmake"
        EXTRA_CMAKE_FLAGS: "-DVC_BUILD_ACVD=ON -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo -DVC_DEVELOPER_WARNINGS=ON"
    tags:
        - test
        - osx
        - homebrew
        - qt6
        - ninja

### Extra Checks and Tests ###
lint:clang-format:
    stage: lint
    needs: []
    before_script:
        - git fetch --all
    script:
        - utils/scripts/clang-format.py --print-output
    allow_failure: true
    tags:
        - clang-format
        - osx
    rules:
        - if: '$CI_PROJECT_URL =~ /.*gitlab\.com.*/'
          when: never
        - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
        - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
          when: never
        - if: '$CI_COMMIT_BRANCH'

### Documentation ###
pages:
    stage: docs
    needs: []
    variables:
        CMAKE_PREFIX_PATH: "/usr/local/opt/qt6/lib/cmake"
    script:
        - mkdir -p build/
        - mkdir -p public/
        - cmake -S . -B build/ -DVC_BUILD_DOCS=ON -DVC_BUILD_APPS=OFF -DVC_BUILD_UTILS=OFF
        - cmake --build build/ --target docs
        - mv build/docs/html/ public/docs/
    artifacts:
        paths:
            - public
    allow_failure: true
    tags:
        - doxy
        - test
    rules:
        - if: '$CI_COMMIT_BRANCH == "develop"'

### Collect & Deploy ###
.deploy_variables: &deploy_variables
    - export DATETIME=$(date '+%Y%m%d')
    - export VERSION=$(utils/scripts/version-gen.sh)
    - export VERSHORT=$(utils/scripts/version-gen.sh --short)
    - export SHA=$(git log -1 --format="%h")

.rules:release: &rules_release
    - if: '$CI_COMMIT_TAG =~ /^v.*$/ && $CI_PROJECT_URL !~ /.*gitlab\.com.*/'

.rules:nightly:collect: &rules_nightly_collect
    - if: $CI_COMMIT_TAG
      when: never
    - if: '$CI_PROJECT_URL =~ /.*gitlab\.com.*/'
      when: never
    - if: '$CI_COMMIT_BRANCH == "develop" && $CI_PIPELINE_SOURCE == "schedule"'
    - if: '$BUILD_NIGHTLY == "true"'

.rules:nightly:deploy: &rules_nightly_deploy
    - if: $CI_COMMIT_TAG
      when: never
    - if: '$CI_PROJECT_URL =~ /.*gitlab\.com.*/'
      when: never
    - if: '$CI_COMMIT_BRANCH == "develop" && $CI_PIPELINE_SOURCE == "schedule"'
    - if: '$CI_COMMIT_BRANCH == "develop" && $BUILD_NIGHTLY == "true"'

.collect:source:
    variables:
        TARNAME: "source.tar.gz"
    script:
        - git archive --format=tar.gz -o ${TARNAME} HEAD
    artifacts:
        name: "${CI_BUILD_STAGE}_${CI_BUILD_REF_NAME}"
        paths:
            - ./*.tar.gz
        expire_in: 1 day
    tags:
        - source

collect:source:release:
    extends:
        - .collect:source
    stage: collect
    needs: []
    rules:
        *rules_release
    before_script:
        - *deploy_variables
        - export TARNAME="VC-${VERSHORT}-source.tar.gz"

collect:source:nightly:
    extends:
        - .collect:source
    stage: collect
    needs: []
    rules:
        *rules_nightly_collect
    before_script:
        - *deploy_variables
        - export TARNAME="VC-${DATETIME}-${VERSHORT}.${SHA}-source.tar.gz"

.macos_move_package: &macos_move_package
    - ninja package
    - mv VC*.dmg ../
    - mv VC*.tar.gz ../

.collect:package:macos:
    extends: .build
    variables:
        CMAKE_PREFIX_PATH: "/usr/local/opt/qt6/lib/cmake"
        EXTRA_CMAKE_FLAGS: "-DCMAKE_BUILD_TYPE=Release -DVC_PREBUILT_LIBS=ON -DVC_BUILD_ACVD=ON -DVC_BUILD_EXAMPLES=OFF -DVC_BUILD_TESTS=OFF"
    before_script:
        - export VC_DEPS_PATH="$CI_PROJECT_DIR/vc-deps"
        - export CMAKE_CMD="cmake -GNinja $EXTRA_CMAKE_FLAGS .."
        - git submodule update --init
        - cd vc-deps/
        - mkdir -p build/
        - cd build/
        - cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DBUILD_UNIVERSAL_LIBS=ON -DVCDEPS_BUILD_ACVD=OFF ..
        - ninja
        - cd ../../
        - export SDKROOT="$CI_PROJECT_DIR/vc-deps/build/osx-sdk-prefix/SDKs/MacOSX${MACOSX_DEPLOYMENT_TARGET}.sdk/"
    script:
        - *build_script
        - *macos_move_package
    artifacts:
        name: "${CI_BUILD_STAGE}_${CI_BUILD_REF_NAME}"
        paths:
            - ./*.dmg
            - ./*.tar.gz
        expire_in: 1 day
    tags:
        - deploy
        - osx
        - qt6

.collect:binaries:macos:release:
    extends:
        - .collect:package:macos
    stage: collect
    rules:
        *rules_release

.collect:binaries:macos:nightly:
    extends:
        - .collect:package:macos
    stage: collect
    rules:
        *rules_nightly_collect
    variables:
        EXTRA_CMAKE_FLAGS: "-DCMAKE_BUILD_TYPE=Release -DVC_VERSION_DATESTAMP=ON -DVC_PREBUILT_LIBS=ON -DVC_BUILD_ACVD=ON -DVC_BUILD_EXAMPLES=OFF -DVC_BUILD_TESTS=OFF"

.upload_final_build:
    variables:
        REMOTE: "volume-cartographer"
    script:
        - mkdir -p ${BUILD_DIR}
        - cp VC*.dmg ${BUILD_DIR}
        - cp VC*.tar.gz ${BUILD_DIR}
        - rclone -v copy ${BUILD_DIR}/ ${REMOTE}:${REMOTE_DIR}/${BUILD_DIR}/
        - export DMG_NAME=$(basename ${BUILD_DIR}/VC-*-Darwin-*.dmg)
        - export DMG_URL=$(rclone link ${REMOTE}:${REMOTE_DIR}/${BUILD_DIR}/${DMG_NAME})
        - export DMG_ID=$(echo ${DMG_URL} | sed 's/https:\/\/drive.google.com\/open?id=//g')
        - echo "${DMG_NAME} → ${DMG_URL}"
        - echo "DMG_ID=${DMG_ID}" >> variables.env
        - export TAR_NAME=$(basename ${BUILD_DIR}/VC-*-Darwin-*.tar.gz)
        - export TAR_URL=$(rclone link ${REMOTE}:${REMOTE_DIR}/${BUILD_DIR}/${TAR_NAME})
        - export TAR_ID=$(echo ${TAR_URL} | sed 's/https:\/\/drive.google.com\/open?id=//g')
        - echo "${TAR_NAME} → ${TAR_URL}"
        - echo "TAR_ID=${TAR_ID}" >> variables.env
    artifacts:
        reports:
            dotenv: variables.env
    tags:
        - rclone

.deploy:release:
    extends:
        - .upload_final_build
    stage: deploy
    needs: ["collect:source:release", "collect:binaries:macos:release"]
    rules:
        *rules_release
    variables:
        REMOTE_DIR: "releases"
    before_script:
        - *deploy_variables
        - export BUILD_DIR=v${VERSION}
    environment:
        name: production

.release:create:
    stage: release
    image: registry.gitlab.com/gitlab-org/release-cli:edge
    needs: ["deploy:release"]
    rules:
        *rules_release
    script:
        - >
            release-cli create
            --name "$CI_COMMIT_TAG"
            --description "Auto-created release $CI_COMMIT_TAG"
            --tag-name "$CI_COMMIT_TAG"
            --ref "$CI_COMMIT_TAG"
            --assets-link "{\"name\":\"macOS ${MACOSX_DEPLOYMENT_TARGET}+ Installer Package\",\"url\":\"https://drive.google.com/open?id=${DMG_ID}\",\"link_type\":\"package\"}"
            --assets-link "{\"name\":\"macOS ${MACOSX_DEPLOYMENT_TARGET}+ Installer Tarball\",\"url\":\"https://drive.google.com/open?id=${TAR_ID}\",\"link_type\":\"package\"}"
    tags:
        - docker

.deploy:nightly:
    extends:
        - .upload_final_build
    stage: deploy
    needs: ["collect:source:nightly", "collect:binaries:macos:nightly"]
    rules:
        *rules_nightly_deploy
    variables:
        REMOTE_DIR: "nightlies"
    before_script:
        - *deploy_variables
        - export BUILD_DIR=${DATETIME}-${VERSHORT}.${SHA}
    environment:
        name: development
